name: Bug Report
description: You have found something wrong with Shiny
title: "[Bug]: "
labels: [bug, unverified]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing an issue.  Please only file issues against the LATEST STABLE version of Shiny from Nuget.  If you are a sponsor, you can discuss issues with preview releases in the SponsorConnect Discord channel
        If you have questions, please post them in GitHub discussions
  - type: dropdown
    id: component
    attributes:
      label: Component/Nuget
      description: The component you are filing against.  If it is not listed here it means there is no support for it
      options:
        - Shiny.Core (Settings, Startup)
        - GPS, Geofencing, Motion Activity (Shiny.Locations)
        - Jobs (Shiny.Jobs)
        - HTTP Transfers (Shiny.Net.Http)
        - Notifications (Shiny.Notifications)
        - NFC (Shiny.Nfc)
        - Push - Native (Shiny.Push)
        - Push - Azure Notification Hub (Shiny.Push.AzureNotificationHubs)
        - Push - Firebase (Shiny.Push.FirebaseMessaging)
        - Push - OneSignal (Shiny.Push.OneSignal)
        - Sensors (Shiny.Sensors)
        - BluetoothLE Client (Shiny.BluetoothLE)
        - BluetoothLE Hosting (Shiny.BluetoothLE.Hosting)
        - Beacons (Shiny.Beacons)
        - SQLite Integration (Shiny.Integrations.Sqlite)
        - AppCenter Logging (Shiny.Logging.AppCenter)
    validations:
      required: true
  - type: checkboxes
    id: platforms
    attributes:
      label: What platform(s) are effected?
      description: You may select more than one.  Only platforms and versions listed here are supported!
      options:
      - label: iOS 12
      - label: iOS 13
      - label: iOS 14
      - label: iOS 15
      - label: Android 8
      - label: Android 9
      - label: Android 10
      - label: Android 11
      - label: Android 12
      - label: UWP (Sponsors ONLY)
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1.
        2.
        3.
  - type: textarea
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: textarea
    id: exception
    attributes:
      label: Exception or Log output
      description: Please copy and paste any relevant log output
  - type: textarea
    id: codesample
    attributes:
      label: Code Sample
      description: Please copy/paste or attach a reproducible sample
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/shinyorg/shiny/blob/master/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
