name: Question
description: Have a question and support OSS or this project, ask away
body:
- type: markdown
  attributes:
    value: |
      Please note that this area is ONLY for active OSS maintainers or ACTIVE project sponsors.  Please leave out questions regarding preview releases
- type: textarea
  attributes:
    label: Question
    description: Please be a concise as possible
    validations:
      required: true
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree that you are a project sponsor or active OSS maintainer 
    options:
      - label: I agree
        required: true