name: .NET Core

on:
  push:
    branches: [ master, dev, preview ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[16.7,16.8)'
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet msbuild -property:Configuration=release -property:BUILD_BUILDNUMBER=$GITHUB_RUN_NUMBER
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
    # - name: dotnet publish
    #  run: dotnet nuget push **\*.nupkg --source https://api.nuget.org/v3/index.json --api-key
