name: Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches:
    - master
    - main
    - dev
    - preview
    - v*

env:
  NugetApiKey: ${{secrets.NUGETAPIKEY}}
  TwitterConsumerKey: ${{secrets.TWITTER_CONSUMER_KEY}}
  TwitterConsumerSecret: ${{secrets.TWITTER_CONSUMER_SECRET}}
  TwitterAccessToken: ${{secrets.TWITTER_ACCESS_TOKEN}}
  TwitterAccessTokenSecret: ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}
  DiscordToken: ${{secrets.DISCORD_TOKEN}}
  DiscordGuildId: '679761126598115336'
  DiscordChannelId: '803717285986566174'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '6.0.400'

    - name: Add .NET 6 Workloads
      run: dotnet workload install maui ios android maccatalyst

    - name: Build
      run: dotnet run --project build/ShinyBuild.csproj

    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nugets
        path: ${{ github.workspace }}/artifacts
        retention-days: 5
