name: .NET Core

on:
  push:
    branches: [ master, dev, preview ]
    paths:
    - "src/**"
  pull_request:
    branches: [ master, dev ]
    paths:
    - "src/**"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[16.7,16.8)'
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet msbuild Build.sln -property:Configuration=release -property:BUILD_BUILDNUMBER=${{ github.run_number }} -property:BUILD_SOURCEBRANCHNAME=${{ github.ref }}
    - name: Publish to nuget
      if: ${{ github.ref == 'dev' || github.ref == 'master' }}
      run: dotnet nuget push **\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NugetApiToken }}
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
