name: Documentation

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install Wyam
      run: dotnet tool install -g Wyam.Tool
    - name: Build Docs with Wyam
      run: wyam build
    - name: Archive
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        directory: s/output
        type: zip
    - name: Post Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: archive-artifact
        path: **/release.zip