name: sponsor 💜
on: 
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  sponsor:
    runs-on: ubuntu-latest
    if: ${{ !endsWith(github.event.sender.login, '[bot]') && !endsWith(github.event.sender.login, 'bot') }}
    steps:
      - name: 💜 sponsor
        uses: devlooped/actions-sponsor@v1
        with:
          # The label to apply to the issue or pull request. 
          # Defaults to "sponsor 💜".
          #label: ''

          # The label to apply when sponsor amount is above the gold-amount. 
          # Defaults to "sponsor 💛".
          #gold-label: ''

          # Sponsors over this amount are labeled with gold-label instead. 
          # Defaults to 100.
          gold-amount: 100

          # The account to check for sponsorship. 
          # Defaults to the repository owner `${{ github.repository.owner }}`
          sponsorable: aritchie

          # The token to use for querying the GitHub API for sponsorship information. 
          # Typically set to ${{ secrets.GH_TOKEN }}.
          token: ${{ secrets.GH_TOKEN }}